### ISSUE TITLE
Issue Template for Exporting internal packages

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#228]
We need an issue template and criteria for exporting a certain internal package. Later, we can discuss the pros and cons on exporting the internal package.

**Comment by vsoch** [comment]
If others want to help with a small list, I'd be happy to take a first shot! What I can remember from the meeting:

- Community discussion on a reliable, stable interface (rationale because exported API needs to be stable)
- Not "hacky"
- Clear user case for having it exported
- ... (I forget the rest!)

**Comment by FeynmanZhou** [comment]
> If others want to help with a small list, I'd be happy to take a first shot! What I can remember from the meeting:
> 
> * Community discussion on a reliable, stable interface (rationale because exported API needs to be stable)
> * Not "hacky"
> * Clear user case for having it exported
> * ... (I forget the rest!)

I can list these questions: 
- Which package
- Pros and cons
- Considerations
- Clear use case

**Comment by shizhMSFT** [comment]
Closing this issue as we don't have many requests of this kind in the last year.
