### ISSUE TITLE
Using http.RoundTripper to make oras-go more extensible

### ISSUE THREAD

**Issue by loresuso** [oras-project/oras-go#361]
Hello everybody,

I am working on [falcoctl](https://github.com/falcosecurity/falcoctl) for adding support to OAuth2.0 and trying to figure out how to make it work and integrate with `oras-go`. In particular, I want to be able to use access tokens until they expire, and then use refresh tokens to get a new one. [This library](https://pkg.go.dev/golang.org/x/oauth2) is perfect for achieving this.

I started looking at the code of this library, in particular at the `auth.Client` and its `Do` function. Basically, from what I can see, the `auth.Client` struct is a wrapper of `http.Client`, adding some more fields to extend the DefaultClient behavior or whatever http.Client is passed. The other observation I made, is that the `Do` function also takes care to resolve authentication if the `Authorization` header is not set. 

Now there are two considerations to make:
- this is a library, so adding a dependency like `oauth2` inside it is not optimal. I think you have done great work in having so few dependencies.
- I feel like I cannot set the authorization header with the access token coming from OAuth *before* the auth.Client.Do function is called (correct me if I am wrong!). 

The possible solution I have in mind is to use the `http.RoundTripper` interface. Instead of wrapping the whole http.Client, we could just implement a new Transport that still has the same code and the same functionalities as the auth.Client has now. By doing so, it could be easier to wrap it inside another RoundTripper, for instance the one that the package OAuth2 implements, taking care of renovating access token when they expire making a post request to a token URL. (https://cs.opensource.google/go/x/oauth2/+/master:transport.go;l=32?q=roundtri&ss=go%2Fx%2Foauth2)

In this way, we could execute in this order: oauth-roundtipper (sets authorization header) -> oras-go roundtripper (skip resolving auth since req already has Authorization) -> DefaultTrasport for actually sending the request. And adding OAuth2 would be external to the library, so no new dependencies.
To not have breaking changes, we could still have a client struct and a method that just set the oras-go roundtripper by default.

I may be completely wrong on this, but I am wide open to discussing this with you! Let me know what you think.

**Comment by shizhMSFT** [comment]
@loresuso I'm not familiar with the `golang.org/x/oauth2` package, and not sure if this package is compatible with the Docker auth flow. It would be great if you can provide a working example of accessing Docker Hub or GHCR using the `oauth2` package such as listing tags.

The reasons why `auth.Client` uses and is a `*http.Client` instead of `http.RoundTripper` are
1. `*http.Client` follows 307 redirect responses, which is essential for fetching blobs, while `http.RoundTripper` does not.
2. The doc of [http.RoundTripper](https://pkg.go.dev/net/http#RoundTripper) states that
   > RoundTrip **should not** attempt to interpret the response. In particular, RoundTrip must return err == nil if it obtained a response, regardless of the response's HTTP status code. A non-nil err should be reserved for failure to obtain a response. Similarly, RoundTrip **should not** attempt to handle higher-level protocol details such as redirects, **authentication**, or cookies.

Moreover, since you are already implementing your own auth client based on `oauth2` package, setting the `Authorization` header. Why not just skip `auth.Client` and use your own implememtation? For example,
```go
repo, err := remote.NewRepository("someregistry.io/somerepo")
if err != nil {
   panic(err)
}
repo.Client = youOwnAuthClient()
```

Besides, if you want to hack, `*http.Client` and `http.RoundTripper` can convert from/to each other. [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp/blob/v0.7.1/client.go#L811) is a good example of conversion.

**Comment by loresuso** [comment]
Thanks a lot Shiwei. 
I didn't know about 307 redirect response for blobs and I didn't consider it. 
Thanks a lot for all the information you gave me, I will try to experiment skipping the `auth.Client` and also trying to hack.
I will update you as soon as possible!

**Comment by loresuso** [comment]
I probably overcomplicated my problem! Thank you @shizhMSFT, with your suggestion I was able to solve it. I think this issue can be closed
