### ISSUE TITLE
improve the error message if failed to resolve a reference in OCI store

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-go#389]
For now, resolving failure will only return `not found` and the context of resolving a reference and what is solved is missing.

**Comment by qweeah** [comment]
@shizhMSFT Can we reopen this since it doesn't cover scenarios when resolving a tag directly without oras.Copy? e.g. `oras manifest fetch` and `oras tag`

**Comment by shizhMSFT** [comment]
> @shizhMSFT Can we reopen this since it doesn't cover scenarios when resolving a tag directly without oras.Copy? e.g. `oras manifest fetch <name>:<non-existent-tag> --oci` and `oras tag <name>:<non-existent-tag> <tag1> --oci`

oras CLI should wrap the error message by itself.

Here's the general guidance. Consider the following call stack:
```go
func A() error {
    return B()
}

func B() error {
    return C()
}

func C() errror {
    // do stuffs
}
```
What if `C()` fails? If we want to make error message verbose, where should we enhance the error message like `fail to C(): <detailed error>`?
- In `C()`? That's not a good idea since `C()` may have many return path for errors. It is also hard to make them consistent. What if `C()` is a virtual method? It is not possible to control all the implementation to output the same error message.
- In `B()`? Probably the best place.
- In `A()`? Not proper since `A()` does not know about `C()`.

Now consider the following call stack: `oras copy` --> `oras.Copy()` --> `Resolver.Resolve()`. It is better to update error messages in `oras.Copy` instead of `Resolver.Resolve()`.

Similarly, for `oras manifest fetch` and `oras tag`, the ORAS CLI should handle the error message properly instead of the `Resolver.Resolve()`.

**Comment by qweeah** [comment]
Can we improve functions in `oras` package? e.g. [oras.Tag](https://github.com/oras-project/oras-go/blob/258bfba7524104a5a76a597184ca0d038f4e3086/content.go#L156) since it does two (fetch and push reference) or three (resolve, fetch and push) operations. Each operation should show different error detail.
