### ISSUE TITLE
Feature request: Adding repo.ReferrersCapability() in oras-go

### ISSUE THREAD

**Issue by patrickzheng200** [oras-project/oras-go#423]
As a user, I'd like to check if a remote registry supports the Referrers API. Currently, I need the following code to do so:
```
const zeroDigest = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
if err := remoteRepo.SetReferrersCapability(true); err != nil {
	return nil, err
}
var checkReferrerDesc ocispec.Descriptor
checkReferrerDesc.Digest = zeroDigest
err := remoteRepo.Referrers(ctx, checkReferrerDesc, "", func(referrers []ocispec.Descriptor) error {
	return nil
})
if err != nil {
	return nil, fmt.Errorf("failed to ping Referrers API with error: %v", err)
}
```
the `remoteRepo.Referrers` is an overhead. Applications that want this check need to have something similar, so probably adding a `repo.ReferrersCapability()` feature in oras-go might save resources for users?

**Comment by Wwwsylvia** [comment]
We may export [pingReferrers()](https://github.com/oras-project/oras-go/blob/main/registry/remote/repository.go#L531-L581) if there is a need.

**Comment by shizhMSFT** [comment]
Since there are multiple solutions / options, why not start a discussion on the design?

**Comment by shizhMSFT** [comment]
> We may export [pingReferrers()](https://github.com/oras-project/oras-go/blob/main/registry/remote/repository.go#L531-L581) if there is a need.

Exporting `pingReferrers()` is a good candidate as we already have an API named `Ping()`.

**Comment by patrickzheng200** [comment]
> We may export [pingReferrers()](https://github.com/oras-project/oras-go/blob/main/registry/remote/repository.go#L531-L581) if there is a need.

Yeah, exporting pingReferrers() would simplify the above logic to a 1-line code since it also sets the repo's `referrersState`.

**Comment by Wwwsylvia** [comment]
This feature was requested for `notation` to determine which manifest type to [pack ](https://pkg.go.dev/oras.land/oras-go/v2#Pack)(OCI Artifact Manifest or OCI Image Manifest).
Given that OCI Artifact Manifest has been deprecated since `image-spec v1.1.0-rc4` (See #494), this scenario is not valid anymore. 
Hence, we can close this issue for now.
Please reopen it if the feature is still needed.

**Comment by Wwwsylvia** [comment]
This feature was requested for notation to determine which manifest type to [pack ](https://pkg.go.dev/oras.land/oras-go/v2#Pack)(OCI Artifact Manifest or OCI Image Manifest).
Given that OCI Artifact Manifest has been deprecated since image-spec v1.1.0-rc4 (See https://github.com/oras-project/oras-go/issues/494), this scenario is not valid anymore.
Hence, we can close this issue for now.
Please reopen it if the feature is still needed.
