### ISSUE TITLE
MediaTypeArtifactManifest not found in v2

### ISSUE THREAD

**Issue by yuseferi** [oras-project/oras-go#495]
Hi there, 
After updating to V2, linter failed with 

```bash
    golangci-lint run ./...        
```

```
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package descriptor: could not load export data: no export data for "oras.land/oras-go/v2/internal/descriptor" 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: buildir: failed to load package descriptor: could not load export data: no export data for "oras.land/oras-go/v2/internal/descriptor"
```

after dig into the code, I noticed this const ( `MediaTypeArtifactManifest`) has not been set in the code.

**Comment by ARolek** [comment]
We're also running into this via Open Policy Agent. Looks like that's your problem as well @yuseferi. https://github.com/open-policy-agent/opa/pull/5769#issuecomment-1531514565

**Comment by Wwwsylvia** [comment]
Do you mean [`application/vnd.oci.artifact.manifest.v1+json`](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/specs-go/v1/mediatype.go#LL59C30-L59C77) or [`application/vnd.cncf.oras.artifact.manifest.v1+json`](https://github.com/oras-project/artifacts-spec/blob/v1.0.0-rc.2/specs-go/v1/mediatype.go#L22)?

- The media type [`application/vnd.oci.artifact.manifest.v1+json`](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/specs-go/v1/mediatype.go#LL59C30-L59C77)  is defined in the OCI [image-spec](https://github.com/opencontainers/image-spec) since [`v1.1.0-rc1`](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc1) , but it just got deprecated in [`v1.1.0-rc.3`](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc.3) by the PR https://github.com/opencontainers/image-spec/pull/999 . We have issue #494 to track the changes in `oras-go`.

- The support for media type [`application/vnd.cncf.oras.artifact.manifest.v1+json`](https://github.com/oras-project/artifacts-spec/blob/v1.0.0-rc.2/specs-go/v1/mediatype.go#L22) has been removed from `oras-go` since [`v2.0.0-rc.4`](https://github.com/oras-project/oras-go/releases/tag/v2.0.0-rc.4).

**Comment by yuseferi** [comment]
Hey @Wwwsylvia ,
if it's depreciated so the usage of the cost should be removed too.  there are lots of them, please search for it in your the codebase.

Best

**Comment by shizhMSFT** [comment]
@yuseferi As mentioned by @Wwwsylvia ans as stated on #494, there is a breaking change in the latest `image-spec v1.1.0-rc.3` that the symbol `MediaTypeArtifactManifest` has been removed. We are discussing how to resolve that accordingly.

**Comment by yuseferi** [comment]
Thank you @shizhMSFT , this issue is breaking lots of projects that are using this package indirectly. mostly https://github.com/open-policy-agent/opa project.  that would be nice to decide about it a bit faster or revert the changes.
Best.

**Comment by shizhMSFT** [comment]
The changes are in the OCI [image-spec](https://github.com/opencontainers/image-spec) repository and thus the ORAS community are not able to revert the changes.

As a solution, I've sent a PR #496 to resolve the compiling error due the missing symbol `MediaTypeArtifactManifest`.
