### ISSUE TITLE
exec oras pull, and set allowpathTraversalonwrite True, and get --output to other directory, but is pull to orginal path

### ISSUE THREAD

**Issue by lht2017** [oras-project/oras-go#750]
when see code in content/file.go
in the method  resolveWritePath, when allowpathTraversalonwrite  is True, then return the original path to store the pull files
is some bug? or it should like this bellow:

![image](https://github.com/oras-project/oras-go/assets/30956002/2ee11d77-acd4-4e88-a08f-978911c4dda1)

**Comment by Wwwsylvia** [comment]
Hi @lht2017 , thanks for opening this issue. 

The purpose of the `resolveWritePath` function is to resolve and validate the target write path of the file name (`name`). If the target path (`path`) is outside of the working directory, it returns `ErrPathTraversalDisallowed`. Otherwise, it returns the absolute path (`path`) of the file name (`name`).
That is, when `AllowPathTraversalOnWrite` is `true`, this function returns the **absolute** path obtained at line `606` (`path := s.absPath(name)`).

https://github.com/oras-project/oras-go/blob/9b6f32158776a699b23edb3db86d053623619b60/content/file/file.go#L604-L633

If you have observed any unexpected behavior, could you please provide additional details? Specifically:

1. What actions did you take, and what were your expectations?
2. What was your environment?
3. How can we reproduce the issue?
4. Are there any relevant error logs?

(We hope to have an [issue template](https://github.com/oras-project/oras-go/issues/641), but it is still [working in progress](https://github.com/oras-project/oras-go/pull/716).)

**Comment by lht2017** [comment]
Thanks for replay!
1. What actions did you take, and what were your expectations?
first I user oras push a file , like /usr/local/tmp/a.txt  to a remote registry ,
then use oras command to pull files from the remote registry, and use param -o , to other directory   like /pull/data/a.txt , but the file a.txt not write in /pull/data/a.txt , actually it always write in the push path, like /usr/local/tmp/a.txt
2 What was your environment?
linux el7
3How can we reproduce the issue?
use step 1

**Comment by Wwwsylvia** [comment]
Hi @lht2017 , this behavior is by design. The `--output` parameter is only applicable to **relative paths**, and the `--allow-path-traversal` means to allow storing files **out of the output directory**.
That is to say, if one specified an absolute path on push, for example `/usr/local/tmp/a.txt`, 
```sh
$ oras push $myrepo:$mytag /usr/local/tmp/a.txt --disable-path-validation
```

they would always get the file pulled to the same location `usr/local/tmp/a.txt`, no matter where `--output` points to.
```sh
oras pull $myrepo:$mytag --output /pull/data/ --allow-path-traversal
```

We just realized that this design could cause user misunderstanding. Do you have any suggestion to help us improve the user experience?
Maybe we can update the documentation for the `--output` parameter to call out that it does not work for absolute paths?

**Comment by FeynmanZhou** [comment]
> Hi @lht2017 , this behavior is by design. The `--output` parameter is only applicable to **relative paths**, and the `--allow-path-traversal` means to allow storing files **out of the output directory**. That is to say, if one specified an absolute path on push, for example `/usr/local/tmp/a.txt`,
> 
> ```shell
> $ oras push $myrepo:$mytag /usr/local/tmp/a.txt --disable-path-validation
> ```
> 
> they would always get the file pulled to the same location `usr/local/tmp/a.txt`, no matter where `--output` points to.
> 
> ```shell
> oras pull $myrepo:$mytag --output /pull/data/ --allow-path-traversal
> ```
> 
> We just realized that this design could cause user misunderstanding. Do you have any suggestion to help us improve the user experience? Maybe we can update the documentation for the `--output` parameter to call out that it does not work for absolute paths?

@qweeah We may consider adding the design philosophy of pull/push on this page to clarify the current behaviors. Users won't be surprised if they are aware of this philosophy in advance.

**Comment by lht2017** [comment]
@Wwwsylvia Thanks，by the way， how can I use oras pull a file to specified other path？

**Comment by lafayetteduarte** [comment]
Hi there.
Im going thru something similar but i am unable to determine the cause.

My aim is to use oras on my pipelines to push artifacts and pull them on other pipelines for the agent to use those artifacts.
To be more precise on the goal, i have some Ansible playbooks ans dependencies that atre maintained on a git repository on my AzureDevops org.

the idea is:  i will have a pipeline on this repo that runs my tests, do some checks , and so on. 

when my pipeline is satisfied with the testing results , it will publish these playbooks as a zip file.
that zip file would be pushed to my registry to be used later from other pipelines that  depends on those playbooks.

Azuredevops agents have the ability to retain tools used by the pipeline. eg a node version can be downloaded via task ( or template) to a specific path on the Agent machine. 

what im trying do to with oras is exactly that. do a oras pull , grab the artifact of the specified version and put it on the tools folder so my next step ( a template can execute that ansible playbook.


so, i have an artifact that is built by my pipeline and then pushed to the registry. So far, so good.
the artifact is pushed and , the org.opencontainers.image.title contains the path where my artifact was originally built. 

<img width="1333" height="410" alt="Image" src="https://github.com/user-attachments/assets/52b791b7-a54c-402a-816f-8494cd6e593d" />

when i try to pull the artifact on another pipeline to be used i'm getting the transversal path error.
i was using the --allow-path-transversal switch 

so, found this issue. trying to wrap my head around the rules , the following question popped into mind:
OK, must be the relative path but, relative to what?
to the oras executable?
to the current working directory?
 
fiddling around the code ( here: https://github.com/oras-project/oras-go/blob/33c6731aff7c9af9ee6af2a5f521acfc33fd7aff/content/file/file.go#L270) , i saw that , the method discussed in this issue (resolveWritePath)  is called passing the value on the title annotation ( the original build path for the artifact). 

does that means that the only valid path ( from where i can derive the relative portion) is the original path where the artifact was built?

is there any way around this? 
After reading the explanations on this post, specially the @Wwwsylvia  remarks on the and i expected that the relative path was a path relative to the current working directory but it seems its relative to the value on the manifest annotation.

I would like to decouple the build path defined on the push action from the path the the consumer will use bc, i could have more than one machine in my Agent pool so, the path on the machine that executed the push will not necessarily exists on the machine using the artifact where the pull will be executed.

thank you.

**Comment by lafayetteduarte** [comment]
Hi @Wwwsylvia  . Appreciate your help on this one.
Yes I can change the directory before performing a push.i will try to change this and run it again.


What is bugging me is the path coupling between the pipeline that produces the artifact and the pipeline that consumes the artifact.

The consumer might not have the same path and or the consumer pipeline might not be able to create the original path .

This can be fixed by both the artifact producing process and the consumer of the artifact agreeing on a common path .

And this prompted a question:
Could this be used by bad actors as a means to inject files ?

In theory it could be done with a combination of the bad actor having the credentials to the registry (seems possible and not really hard to get to ) and the consumer process ( the one doing the pull ) running in a high privileged environment.

So, the bad actor have to know the credentials to do a push , makes a malicious artifact that tries to overwrite config files in , say /etc , pushes this artifact to the registry and waits for someone to pull his version.

If the process doing the pull is using the transverse-path flag and has the proper permissions , it would overwrite the configuration files on push . 

Will try this one later.

Again, really appreciate the help.
