### ISSUE TITLE
Extract warnings to display to the user

### ISSUE THREAD

**Issue by ktarplee** [oras-project/oras-go#757]
The spec describes warnings [here](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#warnings).

One way to expose warning in a backwards compatible and non-invasive way would be to add a callback function to the CopyOptions (or similar) that returns the descriptor and a slice of warnings as strings.  So a field like `warnings func() (ocispec.Descriptor, []string)`.

Obviously the oras CLI should define this function to display the warnings nicely formatted to STDERR.

**Comment by Wwwsylvia** [comment]
Hi @ktarplee , in case you missed it, `oras-go` supports warnings via a callback function `HandleWarning()` of [`Repository`](https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry/remote#Repository). [Here](https://pkg.go.dev/oras.land/oras-go/v2@v2.5.0/registry/remote#example-package-HandleWarning) is an example of configuring this callback.
Since the warning header is specific to the `Repository` target, it is not appropriate to add that to Copy Options. 

Starting from [`v1.1.0`](https://github.com/oras-project/oras/releases/tag/v1.1.0), ORAS CLI  logs the warning messages to STDERR. Here is the related code:  https://github.com/oras-project/oras/blob/9ffdb3eec60b969d842af1a9e699202e0827fa01/cmd/oras/internal/option/remote.go#L273-L288

**Comment by ktarplee** [comment]
I never saw that interface.  Thanks for point it out.  Looks like you have this feature covered well.
