### ISSUE TITLE
Fail to push images to private registries

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-go#97]
`PUT` requests are attempted twice. The body is read for auth and gets empty for the retried requests.

**Comment by shizhMSFT** [comment]
@Wwwsylvia This is the bug we've discussed offline. We need to address it ASAP since it blocks lots of scenarios.

**Comment by Wwwsylvia** [comment]
When we [do PUT request](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L162-L230), we  first attempt to send the request with HTTP Body at [line #162](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L162). If this request failed for Unauthorized error, we will deal with the Auth header and attempt again at [line #203](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L203) or [line #230](https://github.com/oras-project/oras-go/blob/main/registry/remote/auth/client.go#L230).
Since [Request.Clone()](https://pkg.go.dev/net/http#Request.Clone) does not deep copy request Body, the second attempt will read the same Body which has been read by the first attempt, this leads to push error.

Reference: [net/http: Request.Clone() does not deep copy Body contrary to its docs (using GetBody works though)](https://github.com/golang/go/issues/36095)

**Comment by shizhMSFT** [comment]
In fact, `containerd` also has this issue. However, it works because it has the right guess on scope actions (i.e. `pull,push`), and fetches the bearer token when doing `HEAD` requests for the existance check.

We are not able to optimize it at the `auth.Client` level. However, we can fix this bug issue by

1. Guard the `auth.Client` to prevent double read the request body if the body is not rewindable.
2. Optimize `remote.Repository` to make content to be pushed rewindable.
